import pyaudio
import wave
import random
import os
def generate_unique_filename(base_name, extension=".wav"):
    """Generates a unique filename by appending a number if the file exists."""
    if not os.path.exists(f"{base_name}{extension}"):
        return f"{base_name}{extension}"
    
    counter = 1
    while os.path.exists(f"{base_name}_{counter}{extension}"):
        counter += 1
    return f"{base_name}_{counter}{extension}"
abnormal_messages = [
    "my sweet caroline where are you",
    "get out of my head get out stop it",
    "the sky why is the sky so purple today",
    "i told them not to touch my things i told them",
    "i can hear the birds singing can you hear them",
    "is it tuesday i can’t remember if it’s tuesday",
    "i need to find my keys they’re lost somewhere",
    "why is everyone running i just want to sleep",
    "my dog’s coming to pick me up i have to go",
    "i have to go back i forgot my umbrella",
    "the stars are falling i can see them",
    "where’s my homework i need to turn it in",
    "this train is taking me to the moon i’m sure of it",
    "the music is too loud turn it off",
    "don’t touch my shoes they’re mine",
    "the colors are all wrong everything’s wrong",
    "i can’t find the fish where did the fish go",
    "it’s raining inside why is it raining inside",
    "i need to water my plants they’re dying",
    "why is the floor moving it won’t stop",
    "i’m flying look at me i’m flying",
    "the cake’s in the oven it’s going to burn",
    "i need to call my mom she’s waiting for me",
    "there’s sand in my shoes i need to get it out",
    "the walls are closing in they’re too close",
    "it’s so cold here why is it snowing",
    "the clocks won’t stop ticking it’s too loud",
    "i need to finish the painting it’s almost done",
    "they took my hat i need it back",
    "why can’t i find the door it’s always been here",
    "my cat where is my cat she’s hiding from me",
    "i’m late for work i need to get to the office",
    "the ice cream truck is coming i need to get money",
    "get these spiders off me they’re crawling everywhere",
    "i have to bake the cookies before she gets home",
    "where’s the music coming from it won’t stop",
    "the floor is lava don’t step on it",
    "i need to feed the baby she’s crying",
    "the flowers are talking can you hear them too",
    "i’m swimming but i can’t find the shore",
    "stop staring at me everyone’s staring",
    "where’s my boat i was just on it a second ago",
    "i have to catch the train it’s leaving without me",
    "the bees are everywhere get them away",
    "i’m late for my wedding i need to get dressed",
    "i told them not to build the tower so high",
    "why is the grass blue it’s supposed to be green",
    "i need to find my notebook the answers are in there",
    "i’m chasing the butterfly it’s almost in my hand",
    "the floor is upside down how do i stand up",
    "i can feel it i’m fading away",
    "the light’s getting brighter it’s calling me",
    "i need to find my ticket the boat’s leaving without me",
    "where’s my heart i can’t feel my heart anymore",
    "am i supposed to follow the light it’s so far away",
    "the shadows are everywhere they’re swallowing me whole",
    "why is everyone gone am i the only one left",
    "i can’t breathe the air is too thick",
    "is this where i die it’s so cold here",
    "the ground’s sinking i’m falling into it",
    "i think i’m leaving i feel so light",
    "everything’s turning black i can’t see anymore",
    "my hands i can’t feel my hands",
    "i’m not ready to go not yet",
    "is this the end i thought i had more time",
    "the water it’s rising over my head i’m drowning",
    "where is everyone why can’t i hear anyone",
    "i think my time is up it’s over",
    "the voices are telling me to lie down i’m so tired",
    "the stars are pulling me up i’m floating",
    "the ground is eating me alive i can feel it",
    "the sky is closing in on me i can’t escape",
    "why can’t i move my legs they won’t work anymore",
    "i think i’m dying everything’s getting darker",
    "it’s so quiet now too quiet",
    "i’m sinking into the earth it’s pulling me down",
    "where’s my soul i can’t feel it anymore",
    "i think i’m disappearing everything is slipping away",
    "why is the ground so soft it’s like quicksand",
    "is this what dying feels like it’s so cold",
    "i’m not ready yet i need more time",
    "my heart it’s slowing down is this the end",
    "the colors are fading i can’t see them anymore",
    "the darkness is all around me it’s getting closer",
    "i can’t feel anything anymore am i gone",
    "i hear them calling me i think i’m leaving",
    "i’m melting into the ground it’s swallowing me up",
    "where did everyone go i’m all alone now",
    "the walls are closing in on me i can’t breathe",
    "i’m falling deeper and deeper there’s no end",
    "the sun is setting but it’s never going to rise again",
    "is this my grave why can’t i get out",
    "i can see the tunnel should i go through",
    "the end is near i can feel it in my bones",
    "everything’s spinning i can’t hold on any longer",
    "why is it so cold i can’t feel my hands anymore",
    "i hear the bells are they calling me",
    "the light’s fading it’s getting further away",
    "am i dead i can’t feel anything anymore",
    "i’m disappearing like smoke into the wind",
    "i’m slipping away i can’t hold on much longer",
    "the sky is falling it’s pressing down on me",
    "why is it so quiet where did everyone go",
    "i can’t hear my heartbeat anymore is it still there",
    "is this how it ends i thought it would be different",
    "i think i’m leaving everything’s fading",
    "i can’t feel my legs why can’t i move",
    "the ground’s swallowing me i’m sinking",
    "i’m fading into the darkness i can’t stop it",
    "i’m falling apart piece by piece i’m breaking",
    "the end is near i can feel it in my chest",
    "i hear the whispers they’re telling me it’s time to go",
    "i can see the other side it’s not far now",
    "is this the afterlife it’s so quiet here",
    "my body’s gone i can’t feel it anymore",
    "i’m so cold is this what death feels like",
    "i’m sinking into the ground it’s pulling me under",
    "why can’t i move my body won’t listen to me",
    "the sky is falling it’s crashing down on me",
    "i’m fading away like a shadow in the night",
    "i hear the voices they’re calling me to the other side",
    "i’m floating up into the air i can’t stop it",
    "everything’s gone i can’t see anything anymore",
    "i can’t hold on much longer i’m slipping away",
    "the darkness is swallowing me it’s so close now",
    "am i dead i can’t tell anymore",
    "i think i’m gone everything’s so quiet",
    "the ground is pulling me in i can’t get out"
]
# Audio configuration parameters
FORMAT = pyaudio.paInt16  # 16-bit integer format
CHANNELS = 1              # Mono audio
RATE = 44100              # Sampling rate
CHUNK = 1024              # Size of audio buffer (frames per buffer)
RECORD_SECONDS = 5       # Duration to record and playback (in seconds)
# OUTPUT_FILE = "recorded_audio.wav"  # Output file name
original_messages = [
    "Help help help! The train flipped, and I can’t breathe! Ugh, my chest hurts!",
    "What happened? The train just crashed, and I’m trapped under the seats!",
    "Please help, I’m stuck in the third car, can’t move! The train derailed!",
    "Ugh, my head… I think I’m bleeding. The train derailed, can’t feel my arm!",
    "I’m under something heavy! The train just crushed into the ground!",
    "Help! I’m pinched under my seat! The car’s upside down!",
    "The train went off track, and I’m stuck! My leg is stocked between seats!",
    "What? I can’t hear anything! There’s smoke, and I’m trapped in the debris!",
    "The train flipped, and I’m under something! My leg’s bent, can’t move!",
    "Help, help! Ugh, I’m stuck, the windows are broken, and I can’t get out!",
    "The train flipped over! What’s happening? I’m stuck between two chairs!",
    "Ugh, there’s glass everywhere, and I can’t feel my leg! Please, hurry!",
    "The train derailed! I’m stuck in the back. My phone is going to die soon!",
    "Ugh, my leg is trapped under the seat! There’s debris everywhere!",
    "What just happened? The train crashed, and I can’t move my leg!",
    "Help help help! I’m in the last car, and there’s smoke! Can’t see anything!",
    "The train’s gone off the rails! I’m stuck, and I can’t move!",
    "I’m stuck under something, I think it’s a bag? Ugh, help me!",
    "My head’s bleeding! Ugh, can’t see straight, the train’s crashed!",
    "Help! My arm is twisted, and I’m stuck under a chair!",
    "The train derailed, and I’m trapped. Ugh, there’s smoke all around!",
    "I can’t move, my seat’s stuck! The car flipped, and there’s debris!",
    "What? The train flipped? I can’t feel my leg!",
    "The windows are smashed! I’m trapped inside, ugh, I’m bleeding!",
    "Help, I can’t find a way out! The train is upside down, ugh, it hurts!",
    "My leg is pinned! I think the seat fell on me, ugh, it’s so heavy!",
    "What’s going on? The train derailed, and I’m stuck under luggage!",
    "Ugh, I think my arm is broken! I’m stuck under debris!",
    "Help! I can’t breathe, something’s crushing my chest!",
    "The train just crashed! I’m stuck between the seats, can’t get out!",
    "What happened? I’m under something heavy! Ugh, my head is spinning!",
    "Help, help! My leg’s stuck, the train flipped, and I’m bleeding!",
    "Ugh, I can’t feel my leg. The train went off the tracks, and I’m trapped!",
    "What is happening? I’m stuck in my seat, the windows are shattered!",
    "The train derailed! I’m stuck under the chairs, ugh, my head hurts!",
    "Help, I’m bleeding, and I can’t move my arm! Ugh!",
    "Ugh, the car flipped! What do I do? I’m stuck under the seat!",
    "There’s smoke everywhere! Ugh, I’m stuck, and I can’t get out!",
    "What happened? Ugh, my chest… I can’t move, I think it’s broken!",
    "Help, help help! I can’t see anything, and I’m stuck!",
    "What? We crashed? Ugh, my leg is stuck, and I can’t get out!",
    "Help! The plane’s on fire! Ugh, my seatbelt won’t open!",
    "Help help help! Ugh, I’m stuck under the seat, and I can’t breathe!",
    "The plane’s in pieces, and I’m stuck! Ugh, what do I do?",
    "What? I can’t hear! Ugh, there’s fire everywhere, and I’m trapped!",
    "Help! Ugh, I’m pinned under something heavy. I think my arm’s broken!",
    "We crashed, and I’m stuck! My leg is pinned under the seat!",
    "Help! The smoke’s filling the plane! I can’t move!",
    "Ugh, I think my rib’s broken, I’m stuck, the plane’s burning!",
    "Help help help! Ugh, my leg’s twisted, and I can’t move!",
    "What’s happening? The plane crashed, and I’m trapped in my seat!",
    "Ugh, the fire’s spreading! Help, I’m stuck in the back of the plane!",
    "We hit the ground hard! Ugh, I’m pinned under the seat!",
    "Help, the exit’s blocked! I’m stuck, and there’s fire!",
    "Ugh, my arm’s trapped! I can’t get out of the seat!",
    "The plane’s crashed! What do I do? Ugh, I can’t move my leg!",
    "Help help help! Ugh, I’m stuck, the seatbelt won’t open!",
    "The crash threw me into the aisle, ugh, I can’t move!",
    "What? The plane flipped? Ugh, my leg’s pinned under something heavy!",
    "Help, I can’t get out! Ugh, I think my arm is broken!",
    "There’s debris everywhere, ugh, I’m stuck, and I can’t see!",
    "The plane’s on fire, help, ugh, I’m stuck!",
    "What? The plane crashed, and I can’t find a way out!",
    "Ugh, my head’s bleeding, and I’m stuck under the seat!",
    "Help, help! Ugh, I’m trapped in the back of the plane, can’t move!",
    "Ugh, my seatbelt’s stuck, and there’s fire! Help!",
    "The plane hit the ground! Ugh, I can’t feel my leg!",
    "Ugh, my chest hurts, I can’t move, and I’m stuck in my seat!",
    "Help! The plane flipped over! Ugh, I’m trapped!",
    "Ugh, I think my leg’s broken, and I can’t get out!",
    "What’s happening? Ugh, I’m stuck under debris!",
    "Help help help! Ugh, the plane crashed, and I can’t get out!",
    "The plane’s burning! Ugh, I’m stuck in the seat!",
    "Help, I can’t breathe! Ugh, my seatbelt’s jammed!",
    "What just happened? The plane crashed, and I’m trapped under luggage!",
    "Ugh, my head’s spinning, I’m stuck! I can’t move!",
    "Help! Ugh, the fire’s getting closer, and I can’t get up!",
    "Ugh, I’m pinned to the seat! What do I do?",
    "Help, help! Ugh, I can’t feel my arm, and the plane’s on fire!",
    "Ugh, the seatbelt’s stuck, and I can’t get out!",
    "Help! Ugh, I’m trapped, and the smoke’s getting thicker!",
    "What? Ugh, I’m stuck in my seat, and the fire’s spreading!",
    "Ugh, my leg’s stuck under the seat, and I can’t move!",
    "Help! Ugh, the crash pinned me, I can’t feel my arm!",
    "The plane’s filling with smoke! Ugh, I can’t breathe!",
    "Ugh, my leg’s twisted, I’m stuck! Help, help help!",
    "What’s happening? The plane crashed, and I’m pinned!",
    "Help, help! Ugh, I’m stuck in the seat, and I can’t move!",
    "The crash trapped me! Ugh, I think my leg’s broken!",
    "Help! Ugh, my head’s bleeding, and I’m stuck under debris!",
    "Ugh, the smoke’s too thick, I can’t get out!",
    "Help! Ugh, my seatbelt’s stuck, and I’m trapped!",
    "What? Ugh, I’m pinned in my seat, and the fire’s spreading!",
    "Ugh, my arm’s stuck under debris, and I can’t move!",
    "Help, help! Ugh, the plane’s on fire, and I can’t get out!",
    "Ugh, I think my rib’s broken, and I can’t breathe!",
    "The crash flipped the plane! Ugh, I’m trapped under the seat!",
    "What just happened? Ugh, I’m stuck, and the smoke’s filling the plane!",
    "Help! Ugh, I can’t move my leg, and there’s fire everywhere!",
    "Ugh, I’m trapped! I think my seatbelt’s broken, and I can’t get out!"
]
normal_not_emergency_messages = [
    "Hey, I’m okay, what do I do now?",
    "Ugh, I’m safe, but where do I go?",
    "I’m fine here, what’s the next move?",
    "Okay, I’m not hurt. Should I stay here?",
    "What just happened? I’m safe though.",
    "I think I’m good. Do I need to move?",
    "Ugh, I’m a bit sore, but not hurt. Where do I go?",
    "Do I just wait here? I’m safe.",
    "What should I do next? I’m not hurt.",
    "I’m safe, but what’s happening now?",
    "I don’t need help, but where am I supposed to go?",
    "Ugh, what is taking so long? I’m okay though.",
    "Do I need to follow or stay? I’m fine.",
    "I’m totally fine, but what’s next?",
    "I’m alright, should I head to the exit?",
    "What’s going on? I’m not hurt at all.",
    "Okay, I’m safe, so now what?",
    "I think I’m good to go. What do I do?",
    "I’m not hurt, but where’s the others?",
    "What’s my next step? I’m fine.",
    "I’m safe. Is someone coming for me?",
    "Ugh, can you hear me? I’m alright here.",
    "I don’t need medical help. What’s next?",
    "I’m just a little shaken up. Should I move?",
    "Am I supposed to wait here? I’m not injured.",
    "What should I do now? I’m completely fine.",
    "Ugh, I’m alright, just don’t know where to go.",
    "Do I need to go anywhere or just stay put?",
    "I’m safe, but where’s the exit?",
    "I’m fine, but where do I go from here?",
    "I’m okay. Just tell me what’s happening next.",
    "What’s the plan? I’m safe.",
    "I don’t need help, but I need to know what to do.",
    "Should I stay here or go somewhere else?",
    "I’m totally fine, just need directions.",
    "Ugh, I’m safe but confused about what’s next.",
    "What should I do? I feel fine.",
    "I’m not hurt, but do I wait here?",
    "I’m okay, do I need to go anywhere?",
    "What’s happening? I’m safe though.",
    "I’m fine. Is there something I should be doing?",
    "I’m safe, so now what?",
    "What do you want me to do? I’m okay.",
    "I’m just waiting, but I’m fine.",
    "Do I need to move or stay here? I’m safe.",
    "What’s my next step? I’m not injured.",
    "I’m not hurt, but what’s the plan?",
    "Should I just stay put? I’m alright.",
    "What now? I’m safe, just need to know what to do.",
    "I’m safe. Where should I go?",
    "I’m not hurt at all, but what’s next?",
    "Where do I go from here? I’m okay.",
    "I feel fine. What should I be doing?",
    "Do I need to move? I’m alright.",
    "What’s happening next? I’m okay.",
    "I’m completely safe, but where’s the exit?",
    "What do I do now? I’m not hurt.",
    "I’m fine, but I don’t know what’s next.",
    "I’m safe. Do I follow or wait?",
    "Should I go somewhere? I’m not hurt.",
    "I’m safe, just tell me where to go.",
    "I’m not injured. What’s the next move?",
    "What’s the plan now? I’m totally fine.",
    "I’m okay. Where do I need to be?",
    "I don’t need help, but where’s the exit?",
    "What’s next for me? I’m not hurt.",
    "Ugh, I’m safe but stuck here.",
    "I’m not hurt, but should I move?",
    "I’m okay, just tell me what to do next.",
    "What’s the next step? I’m not hurt at all.",
    "I’m safe. Where am I supposed to go?",
    "I’m fine, but what’s the plan?",
    "I’m not injured, but where’s everyone else?",
    "What now? I’m safe and waiting.",
    "I’m okay. What do I need to do now?",
    "I’m safe, but I don’t know where to go.",
    "I feel fine, should I stay here?",
    "I’m not hurt. What’s the next step?",
    "Where’s everyone? I’m okay.",
    "I’m alright, but I’m not sure what to do.",
    "Do I just stay here? I’m fine.",
    "I’m not hurt, but where do I go?",
    "What now? I’m safe, just confused.",
    "I’m okay. Should I move or stay?",
    "I’m not hurt, but what’s the next move?",
    "What should I be doing? I’m okay.",
    "Ugh, I’m safe, but waiting here feels weird.",
    "I’m fine, but where’s everyone else?",
    "What do you need me to do? I’m safe.",
    "I’m not injured, should I stay or move?",
    "I’m completely okay. What should I do next?",
    "What do I do? I’m fine.",
    "I’m okay, but what’s next?",
    "I’m safe, but what’s the next step?",
    "I don’t need help, just directions.",
    "What’s happening now? I’m not hurt.",
    "I’m fine. Where should I be?",
    "Ugh, I’m okay, just need to know where to go.",
    "I’m safe, but where’s the exit?",
    "I’m fine. Do I need to do something?",
    "What do I do next? I’m okay.",
    "I’m not hurt, but where’s everyone?",
    "I’m alright. Just need some direction.",
    "I’m safe. What’s the next step?",
    "What should I do now? I’m fine.",
    "I don’t need help, just tell me where to go.",
    "I’m safe, but what’s the plan?",
    "I’m okay, but where do I go?",
    "What’s next for me? I’m not hurt.",
    "I’m fine. What’s happening next?",
    "I’m safe, but do I need to move?",
    "I’m not injured. Should I wait here?",
    "What do I do now? I’m completely fine.",
    "I’m okay. Where’s everyone else?",
    "I’m safe, but what’s next?",
    "What do I do? I’m not hurt.",
    "I’m alright, but what’s the plan?",
    "Ugh, I’m okay. Just tell me what’s next.",
    "I’m safe, but what now?",
    "I’m fine, should I move or wait?",
    "What’s the next step? I’m safe.",
    "I’m okay, just a little lost.",
    "I’m safe, but I need to know where to go.",
    "What do I need to do? I’m fine.",
    "I’m not hurt, but what’s next for me?",
    "I’m alright, just waiting for instructions.",
    "What’s happening now? I’m safe.",
    "I’m okay, but what’s the next step?",
    "What should I do? I’m not hurt.",
    "I’m fine. Just waiting for the next step.",
    "I’m safe. What do I do now?",
    "I’m alright, but what’s the next move?",
    "Ugh, I’m okay, just don’t know where to go.",
    "I’m safe. What’s the next step?",
    "I’m fine, but where should I be heading?",
    "I’m okay. What’s next for me?",
    "What do I do next? I’m alright.",
    "I’m safe, but what’s the plan?",
    "I’m fine, just need some direction.",
    "I’m okay. What should I do now?",
    "I’m not hurt, but where do I go?",
    "I’m fine, just waiting here. What now?",
    "What’s happening? I’m safe though.",
    "I’m safe, but I don’t know what’s next.",
    "I’m alright, should I be moving?",
    "What’s next for me? I’m safe.",
    "I’m okay, just don’t know what to do.",
    "I’m safe, but where’s everyone else?",
    "I’m fine. Should I be heading somewhere?",
    "What now? I’m safe and waiting.",
    "I’m alright, but what’s the plan?",
    "I’m okay, should I be waiting here?",
    "What should I do? I’m not hurt.",
    "I’m fine, but I’m not sure what’s next.",
    "I’m safe, but where do I go?",
    "What’s next? I’m not hurt at all.",
    "I’m alright, but what’s the next step?",
    "I’m safe. What should I do now?",
    "I’m okay. Where do I need to go?",
    "I’m fine. What’s happening now?",
    "What should I be doing? I’m okay.",
    "I’m safe. What’s the next move?",
    "I’m okay, but I don’t know where to go.",
    "What’s the plan now? I’m safe.",
    "I’m alright, just waiting here.",
    "I’m safe. Do I need to move?",
    "I’m fine. Should I wait here?",
    "What do I do next? I’m alright.",
    "I’m safe. What’s the plan?",
    "I’m okay, just need directions.",
    "I’m fine, just a little confused.",
    "What’s happening now? I’m not hurt.",
    "I’m safe, but where’s everyone?",
    "I’m okay. What’s the next move?",
    "I’m fine. What’s the plan now?",
    "What’s next for me? I’m okay.",
    "I’m safe, but what’s the next step?",
    "I’m okay. Should I wait here?",
    "I’m alright, just need to know what’s next.",
    "I’m fine. Should I move now?",
    "What do I do now? I’m okay.",
    "I’m safe. What’s next for me?",
    "I’m not hurt, just waiting for instructions."
]
def main():
    # Initialize PyAudio
    for i in abnormal_messagesi:
        message = i
        audio = pyaudio.PyAudio()
        OUTPUT_FILE=generate_unique_filename(message)
        print(message)
        x=input("waiting for input")
        # Create a list to store recorded audio data
        frames = []

        try:
            # Open input stream for recording
            stream_input = audio.open(format=FORMAT,
                                    channels=CHANNELS,
                                    rate=RATE,
                                    input=True,
                                    frames_per_buffer=CHUNK)

            # Open output stream for playback
            stream_output = audio.open(format=FORMAT,
                                    channels=CHANNELS,
                                    rate=RATE,
                                    output=True,
                                    frames_per_buffer=CHUNK)

            print("Recording and playing audio in real-time. Speak now!")

            # Record and playback loop
            for _ in range(0, int(RATE / CHUNK * RECORD_SECONDS)):
                try:
                    # Read audio from the input stream
                    audio_data = stream_input.read(CHUNK, exception_on_overflow=False)
                    
                    # Append the audio data to frames for saving
                    frames.append(audio_data)

                    # Write audio to the output stream
                    stream_output.write(audio_data)
                except IOError as e:
                    print(f"Stream error: {e}")
                    break

        finally:
            # Stop and close streams
            stream_input.stop_stream()
            stream_input.close()
            stream_output.stop_stream()
            stream_output.close()

            # Terminate PyAudio
            audio.terminate()

            print("Recording and playback finished.")

            # Save the audio data to a WAV file
            print(f"Saving recorded audio to {OUTPUT_FILE}...")
            with wave.open(OUTPUT_FILE, 'wb') as wf:
                wf.setnchannels(CHANNELS)
                wf.setsampwidth(audio.get_sample_size(FORMAT))
                wf.setframerate(RATE)
                wf.writeframes(b''.join(frames))
            print(f"Audio saved successfully as {OUTPUT_FILE}.")

if __name__ == "__main__":
    main()
